<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MSI" failures="1" tests="1" name="cucumberOptions.FailedTestRunner" time="14.611" errors="0" timestamp="2023-10-19T16:16:06 IST" skipped="0">
  <testcase classname="cucumberOptions.FailedTestRunner" name="runScenario" time="14.611">
    <failure message="expected [No data] but found [Beetroot]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [No data] but found [Beetroot]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at StepDefenitions.OfferPageStepDefinition.user_searched_for_same_shortname_in_offers_page_to_check_if_the_same_product_exists(OfferPageStepDefinition.java:32)
at âœ½.User searched for same shortname Beet in offers page to check if the same product exists(file:///C:/Users/hadim/Documents/MyProjects/Automation_setup/src/test/java/features/SearchProduct.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- cucumberOptions.FailedTestRunner -->
